ALTER TABLE users MODIFY COLUMN time_created DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE cfops MODIFY COLUMN time_created DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE directories MODIFY COLUMN time_created DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE archive_usage MODIFY COLUMN usage_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE transactions MODIFY COLUMN transaction_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE settings MODIFY COLUMN modified DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE settings_values MODIFY COLUMN modified DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE directories ADD CONSTRAINT directory UNIQUE(directory);
ALTER TABLE users ADD CONSTRAINT username UNIQUE(username);
